---
title: "Tables and stuff for poster"
author: "Jenny Sexton"
date: "2025-07-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r packages}
library(sf)
library(ggplot2)
library(tidyverse)
library(readr)
library(corrplot)
library(tmap)
library(RColorBrewer)
library(spdep)
library(spgwr)
library(kableExtra)
```

```{r terrible_table}

setwd("~/R/Birmingham&Walsall/Week3") 
weights_1971 <- read_csv("~/R/Birmingham&Walsall/Week3/weights_1971.csv") %>% rename(prop = prop_ED)
head(weights_1971, 12) 
```

```{r bad table}
Birmingham_084 <- c("E01009366", "E01009374", "E01009376", "E01033648")
weights_tbl <- weights_1971 %>% filter(lsoa21 %in% Birmingham_084) %>% arrange(lsoa21)

kab <- kable(weights_tbl , caption = "Proportion of each 1971 Enumeration District inside each 2021 LSOA", booktabs=T)
kable_classic_2(kab, full_width=F, latex_options="hold_position")
```

```{r best_table}
Birmingham_084C <- "E01009376"
# Load Manufacturing data table for 1971
data_1971 <- read_csv("~/R/Birmingham&Walsall/Week4/Manufacturing_1971.csv") %>% select(zone_code, Total_employed, Manufacturing)

test <- weights_tbl %>% filter(lsoa21 == Birmingham_084C) %>% select(-lsoa21) %>% left_join(data_1971, by = c("ED71ZCD" = "zone_code")) %>%
  relocate(prop, .after = Manufacturing) %>% mutate(Estimate_Employ = round(Total_employed * prop, 2), Estimate_Manufacturing = round(Manufacturing * prop, 2))

Estimate_Employ_Total <- sum(test$Estimate_Employ)
Estimate_Manu_Total <- sum(test$Estimate_Manufacturing)
Reagg_Prop <- round(Estimate_Manu_Total/Estimate_Employ_Total, 2)

test <- test %>% add_row(ED71ZCD = "Reaggregated Total", Estimate_Employ = Estimate_Employ_Total, Estimate_Manufacturing = Estimate_Manu_Total)

kab2 <- kable(test , caption = "Reaggregating percentage", booktabs=T)
kable_classic_2(kab2, latex_options="hold_position")
```







```{r make_maps, echo = FALSE, warning = FALSE}
setwd("~/R/Birmingham&Walsall/Week3") 
Area084_postcodes <- read_sf("Birmingham_084C_pcds.shp") 

# One of the names gets mangled, lets turn it back into something sensible!
Area084_postcodes <- Area084_postcodes %>% rename(in_orig = In_rgn_) 

# Lists of (partially) covered sub-regions for each year before and including 1991
List_ED_1991 <- st_drop_geometry(Area084_postcodes) %>% filter(req_91 == 1) %>% select(ED91CD) %>% distinct() %>% pull()
List_ED_1981 <- st_drop_geometry(Area084_postcodes) %>% filter(req_81 == 1) %>% select(ED81CDO) %>% distinct() %>% pull()
List_ED_1971 <- st_drop_geometry(Area084_postcodes) %>% filter(req_71 == 1) %>% select(ED71ZCD) %>% distinct() %>% pull()

Birmingham_084C <-"E01009376"

# 2021 LSOA boundaries for the Birmingham 084 area
Area084_LSOA_Boundaries_2021 <- read_sf("Lower_layer_Super_Output_Areas_(December_2021)_Boundaries_EW_BFC_(V10).shp") %>% filter(str_detect(LSOA21NM, "Birmingham 084C"))

# 2021 OA boundaries for the Birmingham 084 area
Area084_OA_Boundaries_2021 <- read_sf("OA_2021_EW_BFE_V9.shp") %>% filter(str_detect(LSOA21NM, "Birmingham 084C"))

# Other OA and ED Level geometries
Boundaries_1981 <- read_sf("ED_1981_EW.shp") %>% filter(ED81CDO %in% List_ED_1981) %>% mutate(ED81CDO = as.factor(ED81CDO))
Boundaries_1971 <- read_sf("ED_1971_EW.shp") %>% filter(ED71ZCD %in% List_ED_1971) %>% mutate(ED71ZCD = as.factor(ED71ZCD))
Boundaries_1991 <- read_sf("england_ed_1991.shp") %>% filter(label %in% List_ED_1991) %>% rename(ED91CD = label) %>% mutate(ED91CD = as.factor(ED91CD))

### NICE maps
# Base map without text
Birmingham_084_map <- tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.5, border.col = "black", lwd = 2) + 
  tm_shape(Area084_OA_Boundaries_2021) + tm_borders(lwd = 1) 


# 2021 boundaries LSOA boundaries with OA boundaries inside
Birmingham_084_map0 <- tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.5, border.col = "black", lwd = 2) + 
  tm_shape(Area084_OA_Boundaries_2021) + tm_borders(lwd = 1) #+ 
  #tm_layout(main.title = "2021 OA Boundaries within Birmingham 084C", main.title.size = 1.2, title.position = c("center", "bottom"))
#Birmingham_084_map 

# 1971 Active Postcodes within 2021 Boundaries
Active_postcodes <- Area084_postcodes %>% filter(ac_1991 == 1 & in_orig == 1)
Birmingham_084_map1 <- Birmingham_084_map + tm_shape(Active_postcodes) + tm_dots(size = 0.5) 

# 2021 Boundaries overlayed on 1991 
Birmingham_084_map2 <- tm_shape(Boundaries_1971) + tm_polygons(col = "white", border.col = "black", lwd = 1) + 
  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.5, border.col = "black", lwd = 2)

# 1971 overlapping postcodes on previous map
Active_postcodes <- Area084_postcodes %>% filter(req_71 == 1 & dointr == 198001) %>% mutate(in_orig = as.factor(in_orig))

Birmingham_084_map3 <- tm_shape(Boundaries_1971) + tm_polygons(col = "white", border.col = "black", lwd = 1) + 
  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.5, border.col = "black", lwd = 2) + 
  tm_shape(Active_postcodes) + tm_dots(fill = "black", size = 0.5) + tm_layout(legend.show = FALSE)

# Distinguish between outside and inside 084
Birmingham_084_map4 <- tm_shape(Boundaries_1971) + tm_polygons(col = "white", border.col = "black", lwd = 1) + 
  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.5, border.col = "black", lwd = 2) + 
  tm_shape(Active_postcodes) + tm_dots(fill = "in_orig", col = "in_orig", size = 0.5, palette = "brewer.paired") + tm_layout(legend.show = FALSE)

# Distinguish between outside and inside 084 within each ED
#Birmingham_084_map5 <- tm_shape(Boundaries_1971) + tm_polygons(col = "white", border.col = "black", lwd = 1) + 
#  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "cadetblue1", alpha = 0.25, border.col = "black", lwd = 2) + 
#  tm_shape(Active_postcodes) + tm_dots(fill = "ED71ZCD", col = "ED71ZCD", size = 0.5, palette = "brewer.dark2") + tm_layout(legend.show = FALSE)

#tmap_arrange(Birmingham_084_map0, Birmingham_084_map1, Birmingham_084_map2, Birmingham_084_map3, Birmingham_084_map4, Birmingham_084_map5, ncol = 3) 

############################################

## Percentage of each ED in 2021 LSOA 
weights_1971 <- read_csv("~/R/Birmingham&Walsall/Week3/weights_1971.csv") %>% rename(prop = prop_ED)
Boundaries_1971 <- Boundaries_1971 %>% left_join(weights_1971 %>% filter(lsoa21 == Birmingham_084C)) 
Boundaries_1971 <- Boundaries_1971 %>% mutate(Proportion = round(prop, 2))

Manufacturing_1971 <- read_csv("~/R/Birmingham&Walsall/Week4/Manufacturing_1971.csv")
Manufacturing_1971 <- Manufacturing_1971 %>% mutate(prop_manufacturing = Manufacturing/Total_employed) %>% select(zone_code, prop_manufacturing)
Manufacturing_1971_area084 <- Manufacturing_1971 %>% filter(zone_code %in% List_ED_1971) %>% filter(zone_code != "e39106406034") #remove NaN field


Birmingham_084_map6 <- tm_shape(Boundaries_1971) + tm_polygons(fill = "Proportion", border.col = "black", lwd = 1, palette = "brewer.blues") + 
  tm_labels("Proportion", size = 0.75, col =  "black", fontface = "bold") + tm_layout(legend.position = c("right", "top"), legend.text.size = 0.8,      # Legend text size
  legend.title.size = 1.0)      

#Birmingham_084_map6

## Add on Manufacturing data
Boundaries_1971 <- Boundaries_1971 %>% left_join(Manufacturing_1971_area084, by = c("ED71ZCD" = "zone_code"))
Boundaries_1971 <- Boundaries_1971 %>% mutate(Manufacturing = round(prop_manufacturing, 2))

Birmingham_084_map7 <- tm_shape(Boundaries_1971) + tm_polygons(fill = "Manufacturing", border.col = "black", lwd = 1, palette = "brewer.blues") + 
  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "white", alpha = 0.1, border.col = "black", lwd = 2) + 
  tm_layout(legend.position = c("right", "top"), legend.text.size = 0.8, legend.title.size = 1.0)
   
#Birmingham_084_map7

## Re-aggreated
setwd("~/R/Birmingham&Walsall/Week4") 
Manufacturing_agg <- read_csv("Manufacturing_aggregated.csv") %>% filter(year == 1971 & lsoa21 == Birmingham_084C)

agg_prop <- round(Manufacturing_agg$Manufacturing / Manufacturing_agg$Total_employed, 2)
Area084_LSOA_Boundaries_2021 <- Area084_LSOA_Boundaries_2021 %>% mutate(agg_prop = agg_prop)

Birmingham_084_map8 <- tm_shape(Boundaries_1971) + tm_polygons(col = "white", border.col = "white") + 
  tm_shape(Area084_LSOA_Boundaries_2021) + tm_polygons(col = "agg_prop", border.col = "black", lwd = 2, palette = "brewer.blues") + 
  tm_labels("agg_prop", size = 0.75, col =  "black", fontface = "bold")  + tm_layout(legend.show = FALSE)
```

```{r maps_grid, fig.width=12, fig.height=8, warning = FALSE, message = FALSE}
tmap_arrange(Birmingham_084_map0, Birmingham_084_map1, 
             Birmingham_084_map2, Birmingham_084_map3,
             Birmingham_084_map4, Birmingham_084_map6, 
             Birmingham_084_map7, Birmingham_084_map8, 
             ncol = 2, 
             nrow = 4, asp = 0
             #outer.margins = c(0.05, 0.05, 0.15, 0.05), 
             #inner.margins = 0.01
             #main.title = "Changing between geographical boundaries",
             #main.title.size = 2
             )
```
